import { JSX } from "react";

export const skillIcons: { [key: string]: JSX.Element } = {
  "React": <img src="/icons/react.svg" alt="React" width={24} height={24} />,
  "JavaScript": <img src="/icons/javascript.svg" alt="JavaScript" width={24} height={24} />,
  "TypeScript": <img src="/icons/typescript.svg" alt="TypeScript" width={24} height={24} />,
  "Python": <img src="/icons/python.svg" alt="Python" width={24} height={24} />,
  "Java": <img src="/icons/java.svg" alt="Java" width={24} height={24} />,
  "Kotlin": <img src="/icons/kotlin.svg" alt="Kotlin" width={24} height={24} />,
  "Swift": <img src="/icons/swift.svg" alt="Swift" width={24} height={24} />,
  "C++": <img src="/icons/cplusplus.svg" alt="C++" width={24} height={24} />,
  "C": <img src="/icons/c.svg" alt="C" width={24} height={24} />,
  "C#": <img src="/icons/csharp.svg" alt="C#" width={24} height={24} />,
  "FastAPI": <img src="/icons/fastapi.svg" alt="FastAPI" width={24} height={24} />,
  "Tailwind CSS": <img src="/icons/tailwindcss.svg" alt="Tailwind CSS" width={24} height={24} />,
  "Hugging Face": <img src="/icons/huggingface.svg" alt="Hugging Face" width={24} height={24} />,
  "GPT-2": <img src="/icons/chatgpt.svg" alt="GPT-2" width={24} height={24} />,
  "Aubio": <img src="/icons/aubio.svg" alt="Aubio" width={24} height={24} />,
  "Android Studio": <img src="/icons/androidstudio.svg" alt="Android Studio" width={24} height={24} />,
  "IntelliJ": <img src="/icons/intellij.svg" alt="IntelliJ" width={24} height={24} />,
  "ANTLR": <img src="/icons/antlr.svg" alt="ANTLR" width={24} height={24} />,
  "Z3": <img src="/icons/gear.svg" alt="Z3" width={24} height={24} />,
  "Photon": <img src="/icons/photon.svg" alt="Photon" width={24} height={24} />,
  "Unreal Engine": <img src="/icons/unrealengine.svg" alt="Unreal Engine" width={24} height={24} />,
  "Blueprint": <img src="/icons/blueprint.svg" alt="Blueprint" width={24} height={24} />,
  "Unity": <img src="/icons/unity.svg" alt="Unity" width={24} height={24} />,
  "Vercel": <img src="/icons/vercel.svg" alt="Vercel" width={24} height={24} />,
  "Render": <img src="/icons/render.svg" alt="Render" width={24} height={24} />,
  "GitHub": <img src="/icons/github.svg" alt="GitHub" width={24} height={24} />,
  "GitLab": <img src="/icons/gitlab.svg" alt="GitLab" width={24} height={24} />,
  "Xcode": <img src="/icons/xcode.svg" alt="Xcode" width={24} height={24} />,
  "JIRA": <img src="/icons/jira.svg" alt="JIRA" width={24} height={24} />,
  "Confluence": <img src="/icons/confluence.svg" alt="Confluence" width={24} height={24} />,
  "REST APIs": <img src="/icons/restapi.svg" alt="REST APIs" width={24} height={24} />,
  "Signal Processing": <img src="/icons/signalprocessing.svg" alt="Signal Processing" width={24} height={24} />,
  "NLP": <img src="/icons/nlp.svg" alt="NLP" width={24} height={24} />,
  "Transformer Models": <img src="/icons/transformermodels.svg" alt="Transformer Models" width={24} height={24} />,
  "Prompt Engineering": <img src="/icons/promptengineering.svg" alt="Prompt Engineering" width={24} height={24} />,
  "Local Model Hosting": <img src="/icons/localmodelhosting.svg" alt="Local Model Hosting" width={24} height={24} />,
  "CORS": <img src="/icons/cors.svg" alt="CORS" width={24} height={24} />,
  "Build Pipelines": <img src="/icons/buildpipelines.svg" alt="Build Pipelines" width={24} height={24} />,
  "Environment Variables": <img src="/icons/environmentvariables.svg" alt="Environment Variables" width={24} height={24} />,
  "Linux": <img src="/icons/linux.svg" alt="Linux" width={24} height={24} />,
  "Operating Systems": <img src="/icons/operatingsystems.svg" alt="Operating Systems" width={24} height={24} />,
  "Static Code Analysis": <img src="/icons/staticcodeanalysis.svg" alt="Static Code Analysis" width={24} height={24} />,
  "DSLs": <img src="/icons/dsls.svg" alt="DSLs" width={24} height={24} />,
  "Multithreading": <img src="/icons/multithreading.svg" alt="Multithreading" width={24} height={24} />,
  "Multiplayer Integration": <img src="/icons/multiplayerintegration.svg" alt="Multiplayer Integration" width={24} height={24} />,
  "Game AI": <img src="/icons/gameai.svg" alt="Game AI" width={24} height={24} />,
  "Agile Development": <img src="/icons/agiledevelopment.svg" alt="Agile Development" width={24} height={24} />,
};
